collections:
  staff_members:

title: Frisco
paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

google_analytics_key:

baseurl:

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"
